    </main>
    <footer>
        <div class="copyright">
        © OWL-nest WordPress starter theme by <a href="https://yhunter.ru">Yuri Baranov</a><% if (it.theme) { %><?php echo ', '.date('Y') ?><% } %>
        </div>
   
    </footer>
    </div>

    <link href="@styles/style.scss" rel="stylesheet">
    <script src="@scripts/main.js" defer="defer"></script>
    
    <% if (it.theme) { %>

    <?php wp_footer(); ?>  
 
    <% } %>

    </body>
    </html>