<% if (html) { %>
<%~ include("/src/parts/header.phtml", {html: true}) %>
<% } %>
<% if (theme) { %>
<?php get_header(); ?>
<% } %>

<% if (html) { %>

<article class="entry">

    <div class="entry__image narrow">
        <img src="@images/owl.jpg" alt="Owl photo" />
    </div>
    <div class="entry__textfield">
        <h1>Front page</h1>
        <div class="entry__body">
            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Minus nesciunt, error, minima molestiae quaerat
            itaque nulla omnis neque dignissimos molestias blanditiis adipisci dolore excepturi odit laboriosam aut
            quisquam quibusdam. Quidem.</p>
        </div>
    </div>
    <?php endif; ?>
</article>
<% } %>

<% if (theme) { %>
<?php if (have_posts()) : while (have_posts()) : the_post(); ?>
<article class="entry">
    <?php if ( has_post_thumbnail() ):   ?>
    <div class="entry__image narrow">
        <?php the_post_thumbnail(); ?>
    </div>
    <?php endif; ?>
    <div class="entry__textfield">
        <h1><?php the_title(); ?></h1>
        <div class="entry__body">
            <?php the_content(''); ?>
        </div>
    </div>
    <?php endwhile; ?>
</article>
<?php endif; ?>
<% } %>

<% if (html) { %>
<%~ include("/src/parts/footer.phtml", {html: true}) %>
<% } %>
<% if (theme) { %>
<?php get_footer(); ?>
<% } %>