<% if (html) { %>
<%~ include("/src/parts/header.phtml", {html: true}) %>
<% } %>
<% if (theme) { %>
<?php get_header(); ?>
<% } %>
<article>
<div class="auto-grid" style="
                              --auto-grid-max-columns: 4;
                              --auto-grid-min-size: 18rem;
                              --auto-grid-gap: 1rem;">
    <div class="auto-grid__item"></div>
    <div class="auto-grid__item"></div>
    <div class="auto-grid__item"></div>
    <div class="auto-grid__item"></div>
    <div class="auto-grid__item"></div>
    <div class="auto-grid__item"></div>
    <div class="auto-grid__item"></div>
  </div>

    <img src="@images/owl.jpg" alt="Owl photo" />
    <% if (html) { %>
    <h1>Front Page</h1>

    <% } %>

    <% if (theme) { %>
        <!-- WP Loop -->
        <?php if ( have_posts() ) while ( have_posts() ) : the_post(); // Начало цикла ?>
            <h1><?php the_title(); ?></h1>
            <?php the_content();?>
        <?php endwhile;?>
    <% } %>

</article>

<% if (html) { %>
<%~ include("/src/parts/footer.phtml", {html: true}) %>
<% } %>
<% if (theme) { %>
<?php get_footer(); ?>
<% } %>