<% if (html) { %>
<%~ include("/src/parts/header.phtml", {html: true}) %>
<% } %>
<% if (theme) { %>
<?php get_header(); ?>
<% } %>

<% if (html) { %>
<article class="entry">

    <div class="entry__image narrow">
          <img src="@images/owl.jpg" alt="Owl photo" />
    </div>
    <div class="entry__textfield">
        <h2><a href="">Page title</a></h2>
        <div class="entry__date">01.01.2024</div>
        <div class="entry__body">
            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Minus nesciunt, error, minima molestiae quaerat
            itaque nulla omnis neque dignissimos molestias blanditiis adipisci dolore excepturi odit laboriosam aut
            quisquam quibusdam. Quidem.</p>
        </div>
    </div>
    <?php endif; ?>
</article>
<% } %>

<% if (theme) { %>
<?php if (have_posts()) : while (have_posts()) : the_post(); ?>
<article class="entry">
    <?php if ( has_post_thumbnail() ):   ?>
    <div class="entry__image narrow">
        <?php the_post_thumbnail(); ?>
    </div>
    <?php endif; ?>
    <div class="entry__textfield">
        <h2><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h2>
        <div class="entry__date"><?php the_time('F j, Y');?></div>
        <div class="entry__body">
            <?php the_content(''); ?>
        </div>
        <div class="entry__meta meta">
            <div class="meta__cats">
                <?php echo 'Categories: '; the_category( ', ' );  ?>
            </div>
            <div class="meta__tags">
                <?php the_tags( 'Tags: ', ', ', ' ' ); ?>
            </div>
        </div>
    </div>
    <?php endwhile; ?>
</article>
<?php endif; ?>
<% } %>

<% if (html) { %>
<%~ include("/src/parts/pagination.phtml", {html: true}) %>
<% } %>
<% if (theme) { %>
<%~ include("/src/parts/pagination.phtml", {theme: true}) %>
<% } %>


<% if (html) { %>
<%~ include("/src/parts/footer.phtml", {html: true}) %>
<% } %>
<% if (theme) { %>
<?php get_footer(); ?>
<% } %>