<% if (html) { %>
<%~ include("/src/parts/header.phtml", {html: true}) %>
<% } %>
<% if (theme) { %>
<?php get_header(); ?>
<% } %>

<% if (html) { %>

<article class="entry">

    <div class="entry__image narrow">
        <img src="@images/owl.jpg" alt="Owl photo" />
    </div>
    <div class="entry__textfield">
        <h1>Single title</h1>

        <div class="entry__date">01.01.2024</div>
        <div class="entry__body">
            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Minus nesciunt, error, minima molestiae quaerat
            itaque nulla omnis neque dignissimos molestias blanditiis adipisci dolore excepturi odit laboriosam aut
            quisquam quibusdam. Quidem.</p>
        </div>
        <div class="entry__meta meta">
            <div class="meta__cats">
                Categories: <a href="">cat1</a>
            </div>
            <div class="meta__tags">
                Tags: <a href="">tag1</a>
            </div>
        </div>
    </div>
</article>
<% } %>

<% if (theme) { %>
<?php if (have_posts()) : while (have_posts()) : the_post(); ?>
<article class="entry">
    <?php if ( has_post_thumbnail() ):   ?>
    <div class="entry__image narrow">
        <?php the_post_thumbnail(); ?>
    </div>
    <?php endif; ?>
    <div class="entry__textfield">
        <h1><?php the_title(); ?></h1>
        <div class="entry__date"><?php the_time('F j, Y');?></div>
        <div class="entry__body">
            <?php the_content(''); ?>
        </div>
        <div class="entry__meta meta">
            <div class="meta__cats">
                <?php echo 'Categories: '; the_category( ', ' );  ?>
            </div>
            <div class="meta__tags">
                <?php the_tags( 'Tags: ', ', ', ' ' ); ?>
            </div>
        </div>
    </div>
    <?php endwhile; ?>
</article>
<?php endif; ?>
<% } %>

<div class="pagination">
<% if (html) { %>
    <a href="">Previous post title</a>
    <a href="">Next post title</a>
    <% } %>
<% if (theme) { %>
    <?php previous_post_link( '%link',  '%title');?>
    <?php next_post_link( '%link', '%title'); ?>
<% } %>
</div>

<% if (html) { %>
<%~ include("/src/parts/footer.phtml", {html: true}) %>
<% } %>
<% if (theme) { %>
<?php get_footer(); ?>
<% } %>